# Generated by Django 2.1.5 on 2020-03-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('border', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='border',
            name='싫어요',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='border',
            name='좋아요',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='border',
            name='조회수',
            field=models.IntegerField(default=0),
        ),
    ]
